# Generated by Django 4.1.3 on 2022-11-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DominikRadziszewski", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameOfPost", models.CharField(max_length=64)),
                ("descriptionOfPost", models.TextField(max_length=1024)),
                (
                    "categoryOfPost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DominikRadziszewski.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PicturesOfPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pictureOfPost",
                    models.ImageField(
                        blank=True, null=True, upload_to="pictures_of_post"
                    ),
                ),
                (
                    "whichPost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DominikRadziszewski.post",
                    ),
                ),
            ],
        ),
    ]
