# Generated by Django 4.1.3 on 2022-11-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DominikRadziszewski', '0004_rename_descriptionofcontat_contact_descriptionofcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturesofpost',
            name='descriptionOfPicture',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
