# Generated by Django 4.1.3 on 2022-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DominikRadziszewski', '0005_picturesofpost_descriptionofpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linkToSite',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
