# Generated by Django 4.1.3 on 2022-12-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DominikRadziszewski', '0006_post_linktosite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='samplePrice',
            field=models.PositiveSmallIntegerField(blank=True, default=300, null=True),
        ),
    ]
